name: Build Workflow

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: ${{ matrix.os == 'macos-latest' && 'arm64' || 'x64' }}
          cache: 'pip'
          cache-dependency-path: |
            **/pyproject.toml

      - name: Install Dependencies
        run: |
          pip install .

      - name: Build Executable for macOS
        if: matrix.os == 'macos-latest'
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/aniworld
          onefile: true
          macos-create-app-bundle: true
          output-dir: build

      - name: Build Executable for other OS
        if: matrix.os != 'macos-latest'
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/aniworld
          onefile: true
          output-dir: build

      - name: Upload Artifacts for macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macOS Build
          path: build/*.app/**/*

      - name: Upload Artifacts for other OS
        if: matrix.os != 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/**/*.*
          include-hidden-files: true
